#!/bin/bash
#Simple bash script to reset both databases

#Reset "sandbox" database
read -p "DB User:  " U
read -p "Password:  " P
mysql -u$U -p$P <<< 'source trysql_data_create.sql'

#Reset rails application
rake db:drop
rake db:setup
